// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderManagement.Data;

#nullable disable

namespace OrderManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241101013545_UpdateRelation")]
    partial class UpdateRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderManagement.Models.Customer", b =>
                {
                    b.Property<int>("COM_CUSTOMER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("COM_CUSTOMER_ID"));

                    b.Property<string>("CUSTOMER_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("COM_CUSTOMER_ID");

                    b.ToTable("COM_CUSTOMER");
                });

            modelBuilder.Entity("OrderManagement.Models.SOItem", b =>
                {
                    b.Property<long>("SO_ITEM_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ITEM_ID"));

                    b.Property<string>("ITEM_NAME")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PRICE")
                        .HasColumnType("float");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int");

                    b.Property<long?>("SOOrderSO_ORDER_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("SO_ORDER_ID")
                        .HasColumnType("bigint");

                    b.HasKey("SO_ITEM_ID");

                    b.HasIndex("SOOrderSO_ORDER_ID");

                    b.ToTable("SO_ITEM");
                });

            modelBuilder.Entity("OrderManagement.Models.SOOrder", b =>
                {
                    b.Property<long>("SO_ORDER_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SO_ORDER_ID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("COM_CUSTOMER_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ORDER_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ORDER_NO")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SO_ORDER_ID");

                    b.ToTable("SO_ORDER");
                });

            modelBuilder.Entity("OrderManagement.Models.SOItem", b =>
                {
                    b.HasOne("OrderManagement.Models.SOOrder", null)
                        .WithMany("Items")
                        .HasForeignKey("SOOrderSO_ORDER_ID");
                });

            modelBuilder.Entity("OrderManagement.Models.SOOrder", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
